### ISSUE TITLE
"$normalizedKey" is not always string in some conditions

### ISSUE THREAD

**Issue by menturion** [laminas/laminas-cache-storage-adapter-session#5]
Please explicitly cast `$normalizedKey` to string (-> `(string)$normalizedKey`) in all places where it is being used as array key.

Just one example, instead of...
https://github.com/laminas/laminas-cache-storage-adapter-session/blob/b32912335b47c21990b4637e7acff55273b9f384/src/Session.php#L157-L162

use...

```
        $success = array_key_exists((string)$normalizedKey, $data);
        if (! $success) {
            return;
        }


        $casToken = $value = $data[(string)$normalizedKey];
```

**Comment by Ocramius** [comment]
@menturion that method expects a `string` as input, so no cast is required:

https://github.com/laminas/laminas-cache-storage-adapter-session/blob/b32912335b47c21990b4637e7acff55273b9f384/src/Session.php#L140

**Comment by boesing** [comment]
@Ocramius the problem is, that it is not always a string afair.

@menturion could you provide some more informations on how to reproduce the problem? 
I know that there are some annoying conditions where some types within the cache library are not correct.

Would love to have some kind of "flow" where I can follow the steps/problems which lead to the case that `normalizedKey` is not a string.

Just to say: I am not sure if the underlying problem is in this package. But I'd like to use this issue to gather informations for reproduction. I think the bugfix will land in laminas-cache.

**Comment by Ocramius** [comment]
> @Ocramius the problem is, that it is not always a string afair.

That's up to the caller to solve

**Comment by menturion** [comment]
>  think the bugfix will land in laminas-cache.

I think it should land on adapter level, because ....

-1- type casting of "$normalizedKey" is already done for other adapters and 
-2- it should be done while iterating through "$normalizedKeys" arrays

and, IMHO, once you are doing it in one location of an adapter you should do it consistently throughout this adapter.

Just three examples ...

- Apc -
https://github.com/laminas/laminas-cache-storage-adapter-apc/blob/6e8cbd5c2fe0ca471c4b01e1eaf34c0a29481166/src/Apc.php#L248

- Apcu -
https://github.com/laminas/laminas-cache-storage-adapter-apcu/blob/22f13a378ea3042b102d839224436b26132ad4d6/src/Apcu.php#L243

- Redis -
https://github.com/laminas/laminas-cache-storage-adapter-redis/blob/a306d94cf804b509c4da6c2b81ce872f53b2a673/src/Redis.php#L179


Whether you do it like `'' . $normalizedKey` or `(string)$normalizedKey` might be a matter of micro-optimization.

**Comment by boesing** [comment]
As I said, and as @Ocramius said, unless you dont have a failing example, we wont ship a fix.
just because php is some how "fail safe" with string concatenation as you pointed to, does not solve the issue. 

If userland code extends the methods which are consuming these keys which meant to be string, that code would have to cast aswell. 
To solve this, we should ensure that the underlying abstraction (`AbstractAdapter`) will send only strings. 

This will also solve future problems when we start implementing native typehint. 

So please provide some kind of flow so we can see where the real problem is. 

Type has to be string as per docblock. So there wont be any type cast ever in this package. 


As you can see [here](https://github.com/laminas/laminas-cache/blob/7fbe260f9b7928bae0723f17600b053b07640f74/src/Storage/Adapter/AbstractAdapter.php#L1510), it is already ensured that key should be string. Somehow, its not anymore and we definitely have to find out when the type-change happens.

As you considered a problem I'd think that you can help us finding the real issue.
